### ISSUE TITLE
[Question]: Can you move the buddingcrystals folder to configs folder?

### ISSUE THREAD

**Issue by Mysticpasta1** [XFactHD/BuddingCrystals#12]
Title

**Comment by XFactHD** [comment]
You'll have to explain why that's benefitial. I very intentionally placed that folder outside of configs because the files in there are very different from normal configs. As far as I'm aware, most other mods with special files such as KubeJS also place them outside of the configs folder for this reason.

**Comment by Mysticpasta1** [comment]
ah ok idk they did that I will close the issue :D
